name: Build and Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          cache: gradle

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Run Tests (PR Only)
        if: github.event_name == 'pull_request'
        run: ./gradlew test

      - name: Build Project (Push Only)
        if: github.event_name == 'push'
        run: ./gradlew build

      - name: Capture Build Artifacts
        if: github.event_name == 'push' && matrix.java == 21
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
