name: GitHub to Discord Webhook

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Repository name"
        required: true
        type: string
      branch_name:
        description: "Branch name"
        required: true
        type: string
      event_type:
        description: "Event type (commit, pull-request, issues)"
        required: true
        type: string
      commit_sha:
        required: false
        type: string
      commit_message:
        required: false
        type: string
      commit_author:
        required: false
        type: string
      pr_title:
        required: false
        type: string
      pr_body:
        required: false
        type: string
      pr_url:
        required: false
        type: string
      pr_number:
        required: false
        type: string
      pr_author:
        required: false
        type: string
      pr_state:
        required: false
        type: string
      pr_merged:
        required: false
        type: boolean
      issue_title:
        required: false
        type: string
      issue_body:
        required: false
        type: string
      issue_url:
        required: false
        type: string
      issue_number:
        required: false
        type: string
      issue_author:
        required: false
        type: string
      issue_state:
        required: false
        type: string

jobs:
  send_webhook:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21

      - name: Execute Kotlin Webhook
        working-directory: workflow
        env:
          DISCORD_COMMIT_WEBHOOK: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
          DISCORD_PR_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
          DISCORD_ISSUE_WEBHOOK: ${{ secrets.DISCORD_ISSUE_WEBHOOK }}
          GITHUB_REPOSITORY: ${{ inputs.repo_name }}
          GITHUB_REF: ${{ inputs.branch_name }}
          GITHUB_SHA: ${{ inputs.commit_sha }}
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ inputs.commit_message }}
          GITHUB_ACTOR: ${{ inputs.commit_author || inputs.pr_author || inputs.issue_author }}
          GITHUB_PR_TITLE: ${{ inputs.pr_title }}
          GITHUB_PR_BODY: ${{ inputs.pr_body }}
          GITHUB_PR_URL: ${{ inputs.pr_url }}
          GITHUB_PR_NUMBER: ${{ inputs.pr_number }}
          GITHUB_PR_AUTHOR: ${{ inputs.pr_author }}
          GITHUB_PR_STATE: ${{ inputs.pr_state }}
          GITHUB_PR_MERGED: ${{ inputs.pr_merged }}
          GITHUB_EVENT_TYPE: ${{ inputs.event_type }}
          GITHUB_ISSUE_TITLE: ${{ inputs.issue_title }}
          GITHUB_ISSUE_BODY: ${{ inputs.issue_body }}
          GITHUB_ISSUE_URL: ${{ inputs.issue_url }}
          GITHUB_ISSUE_NUMBER: ${{ inputs.issue_number }}
          GITHUB_ISSUE_AUTHOR: ${{ inputs.issue_author }}
          GITHUB_ISSUE_STATE: ${{ inputs.issue_state }}

        run: ./gradlew run --args="-${{ inputs.event_type }}"
