name: Receive and Notify Discord

on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Base64-encoded JSON payload'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Decode payload
        run: |
          echo "${{ inputs.payload }}" | base64 -d > payload.json

      - name: Run Discord Dispatcher
        env:
          DISCORD_COMMIT_WEBHOOK: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
          DISCORD_ISSUE_WEBHOOK: ${{ secrets.DISCORD_ISSUE_WEBHOOK }}
          DISCORD_PR_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
        run: ./gradlew run --args="payload.json"
